const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {Text,Element,parseHTML,createDocument}=require('./i18n-test-dom.cjs');
const root=path.join(__dirname,'..');
const document=createDocument(),storage=new Map();
const app=document.body.append(new Element('div',{id:'app'},document));
const modal=document.body.append(new Element('div',{id:'modal-root'},document));
const toast=document.body.append(new Element('div',{id:'toast'},document));
const context={console,Intl,Date,Map,Set,WeakMap,URL,URLSearchParams,JSON,Number,String,Array,Math,RegExp,Error,Promise,Blob,document,window:{addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:()=>'',setItem(){},removeItem(){}},location:{origin:'http://localhost:8080',pathname:'/studio/new',search:'',href:'http://localhost:8080/studio/new'},history:{replaceState(){}},navigator:{},crypto:{randomUUID:()=>Math.random().toString(16)},setTimeout:()=>1,clearTimeout(){},queueMicrotask:fn=>fn(),CustomEvent:class{constructor(type,{detail}){this.type=type;this.detail=detail;}},fetch:async()=>({ok:true,status:200,json:async()=>({ok:true,data:{}})})};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'i18n.js'),'utf8'),context);
const i18n=context.window.FolioI18n;
const enKeys=Object.keys(i18n.dictionaries.en),zhKeys=Object.keys(i18n.dictionaries['zh-CN']);assert.deepEqual(enKeys,zhKeys);assert.equal(new Set(i18n.entries.map(e=>e[0])).size,i18n.entries.length,'no duplicate semantic keys');for(const key of enKeys){assert.ok(i18n.dictionaries.en[key]);assert.ok(i18n.dictionaries['zh-CN'][key]);const params=v=>[...v.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort();assert.deepEqual(params(i18n.dictionaries.en[key]),params(i18n.dictionaries['zh-CN'][key]),`placeholder parity: ${key}`);}
assert.equal(i18n.locale,'zh-CN');assert.equal(document.documentElement.lang,'zh-CN');assert.equal(storage.get('folio.locale'),'zh-CN');assert.match(document.cookie,/folio\.locale=zh-CN/);
assert.equal(i18n.text('24 words · 2 min read'),'24 字／词 · 约 2 分钟阅读');assert.equal(i18n.text('Revision 3 · live'),'第 3 版 · 已上线');assert.equal(i18n.text('2 results for “Settings”'),'“Settings”的搜索结果：2 条');
assert.equal(i18n.text('A valid Bearer token is required'),'需要有效的 Bearer 访问令牌');
// Pure migration diagnostics stay canonical in plans, but their UI explanations translate.
for(const file of ['parse.go','types.go','plan.go']){
 const diagnostics=fs.readFileSync(path.join(root,'..','internal','migration',file),'utf8');
 for(const match of diagnostics.matchAll(/fmt\.Errorf\("([^"\n]+)"/g)){
  const sample=match[1].replaceAll('%d','3').replaceAll('%s','tags').replaceAll('%w','invalid double-quoted scalar');
  assert.ok(i18n.resolve(sample),`migration diagnostic: ${sample}`);assert.match(i18n.text(sample),/\p{Script=Han}/u,`Chinese migration diagnostic: ${sample}`);
 }
}
assert.equal(i18n.text('metadata custom_field: invalid double-quoted scalar'),'元数据 custom_field：双引号标量无效');
assert.equal(i18n.text('Invalid migration plan: plan checksum mismatch'),'迁移计划无效：计划校验值不匹配');
assert.equal(i18n.text('元数据 custom_field：双引号标量无效'),'元数据 custom_field：双引号标量无效');
assert.equal(i18n.text('metadata custom_field: future provider detail'),'元数据 custom_field：future provider detail','unknown detail stays verbatim');
i18n.setLocale('en');assert.equal(i18n.text('元数据 custom_field：双引号标量无效'),'metadata custom_field: invalid double-quoted scalar');assert.equal(i18n.text('迁移计划无效：计划校验值不匹配'),'Invalid migration plan: plan checksum mismatch');i18n.setLocale('zh-CN');

const ui=parseHTML('<div><button id="ui">Settings</button><h1 data-no-i18n>Settings</h1><h2 data-no-i18n>Journal</h2><a data-no-i18n>Drafts</a><p data-no-i18n>No activity yet.</p><div class="prose"><p>Save draft</p></div><textarea id="buffer">Save draft</textarea><input id="input" placeholder="Give your idea a title…"><button aria-label="Read Settings">Read the story</button><time data-i18n-date="2026-10-03T15:00:00Z">Oct 3, 2026</time><span id="counter">24 words · 2 min read</span></div>',document);document.body.append(ui);const buffer=ui.querySelector('#buffer');buffer.value='Save draft\n正在输入';buffer.selectionStart=3;buffer.selectionEnd=8;buffer.scrollTop=44;buffer.focus();
i18n.apply(ui);assert.equal(ui.querySelector('#ui').textContent,'设置');assert.equal(ui.querySelector('#ui').getAttribute('data-i18n'),'nav.settings');assert.equal(ui.querySelector('[data-no-i18n]').textContent,'Settings');assert.equal(ui.querySelector('.prose').textContent,'Save draft');assert.equal(buffer.textContent,'Save draft');assert.equal(ui.querySelector('#input').getAttribute('placeholder'),'给这个想法起个名字……');assert.equal(ui.querySelector('[aria-label]').getAttribute('aria-label'),'阅读：Settings');assert.match(ui.querySelector('time').textContent,/2026/);assert.ok(!ui.querySelector('time').textContent.includes('Oct'));
i18n.setLocale('en');assert.equal(ui.querySelector('#ui').textContent,'Settings');assert.equal(ui.querySelector('#counter').textContent,'24 words · 2 min read');assert.equal(ui.querySelector('#input').getAttribute('placeholder'),'Give your idea a title…');assert.equal(ui.querySelector('[aria-label]').getAttribute('aria-label'),'Read Settings');assert.equal(document.activeElement,buffer);assert.equal(buffer.value,'Save draft\n正在输入');assert.equal(buffer.selectionStart,3);assert.equal(buffer.selectionEnd,8);assert.equal(buffer.scrollTop,44);assert.equal(document.documentElement.lang,'en');
// Textarea values/default text are authored content; their UI attributes are not.
const textareaUI=parseHTML('<textarea id="localized-buffer" placeholder="Start writing. There’s no rush…" aria-label="Story Markdown" title="Story title">Save draft</textarea>',document);
document.body.append(textareaUI);
const localizedBuffer=textareaUI.querySelector('#localized-buffer'),defaultText=localizedBuffer.childNodes[0];
localizedBuffer.value='Settings\n保留正在编辑的内容';localizedBuffer.selectionStart=2;localizedBuffer.selectionEnd=7;localizedBuffer.scrollTop=31;localizedBuffer.focus();
for(const locale of ['zh-CN','en','zh-CN','en']){
 i18n.setLocale(locale);i18n.apply(textareaUI);
 for(const [attribute,key] of [['placeholder','editor.body.placeholder'],['aria-label','editor.markdown'],['title','editor.title']])assert.equal(localizedBuffer.getAttribute(attribute),i18n.dictionaries[locale][key],`textarea ${attribute} changes to ${locale}`);
 assert.equal(localizedBuffer.childNodes[0],defaultText);assert.equal(defaultText.nodeValue,'Save draft');assert.equal(localizedBuffer.value,'Settings\n保留正在编辑的内容');assert.equal(document.activeElement,localizedBuffer);assert.equal(localizedBuffer.selectionStart,2);assert.equal(localizedBuffer.selectionEnd,7);assert.equal(localizedBuffer.scrollTop,31);
}
// Explicit user-content boundaries must continue to exclude attributes, even on textareas.
for(const wrapper of ['<div data-no-i18n>','<div class="prose">','<div class="code-sample">','<div class="tools-output">','<pre>','<code>','<script>','<style>']){
 const protectedUI=parseHTML(`${wrapper}<textarea placeholder="Start writing. There’s no rush…" aria-label="Story Markdown" title="Story title">Save draft</textarea>`,document);
 i18n.setLocale('zh-CN');i18n.apply(protectedUI);const field=protectedUI.querySelector('textarea');
 assert.equal(field.getAttribute('placeholder'),'Start writing. There’s no rush…');assert.equal(field.getAttribute('aria-label'),'Story Markdown');assert.equal(field.getAttribute('title'),'Story title');assert.equal(field.textContent,'Save draft');
}
const optedOut=parseHTML('<textarea data-no-i18n placeholder="Start writing. There’s no rush…">Save draft</textarea>',document);i18n.apply(optedOut);assert.equal(optedOut.querySelector('textarea').getAttribute('placeholder'),'Start writing. There’s no rush…');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8').replace('  render();\n})();','  globalThis.test={state,words,home,topics,tagPage,about,article,searchPage,login,studioPosts,editorView,settingsPage,mediaPage,toolsPage,revisionHistoryMarkup,saveDraft,proposalsPage,schedulesPage,proposalReviewHTML,migrationPage,migrationPlanView,migrationReportView};\n})();');vm.runInContext(source,context);const api=context.test;
const post={id:'post-1',title:'Settings',slug:'journal',excerpt:'No activity yet.',markdown:'Save draft',html:'<p>Save draft</p>',tags:['Drafts'],category:'Journal',featured:true,revision:1,published_revision:0,created_at:'2026-10-03T15:00:00Z',updated_at:'2026-10-03T15:00:00Z',published_at:'2026-10-03T15:00:00Z'};
api.state.site={settings:{title:'Journal',author:'Settings',description:'No activity yet.',base_url:'http://localhost:8080'},posts:[post,{...post,id:'post-2',slug:'other',featured:false}]};api.state.editor={post,revisions:[post]};
const capabilitySource=['capabilities.go','proposals.go','schedules.go','migration.go'].map(file=>fs.readFileSync(path.join(root,'..','internal','core',file),'utf8')).join('\n');
const operations=[...capabilitySource.matchAll(/(?:add\(|Spec\{)"([^"]+)", "([^"]+)"/g)].map(m=>({name:m[1],description:m[2],scope:'read',read_only:true,input_schema:{type:'object',properties:{title:{type:'string'}}}}));
const proposal={id:'proposal-1',post_id:post.id,base_revision:1,revision:1,status:'pending',created_by:'proposal',created_at:post.created_at,candidate:{...post,title:'Settings'},base:{...post}};
const review={changed_fields:[{field:'title',before:'Journal',after:'Settings'},{field:'markdown',before:'Save draft',after:'<img src=x onerror=alert(1)>'}],markdown_diff:[{kind:'remove',text:'Save draft'},{kind:'add',text:'<img src=x onerror=alert(1)>'}]};
const schedule={id:'schedule-1',post_id:post.id,post_revision:1,revision:1,status:'pending',snapshot:post,publish_at:'2030-01-01T12:00:00Z'};
const migrationDocument={source_path:'Settings.md',title:'Settings',slug:'journal',markdown:'Save draft',date:'2020-01-01T00:00:00Z',publish_date:'2020-02-01T00:00:00Z',extra:{layout:'Drafts'},warnings:['draft:false is source metadata only; import always saves a private draft','date retained as metadata; existing posts API cannot set historical timestamps or schedule publication','unsupported metadata retained, not applied: layout','title inferred from first H1 or filename','slug inferred from filename; non-ASCII filename uses stable path hash','attachment references preserved verbatim; no attachment copied, uploaded, rewritten, or remotely fetched']};
const migrationReview={target_instance_id:'Settings',can_apply:false,plan:{entries:['create','update','skip','blocked'].map(action=>({action,document:migrationDocument,expected_revision:3})),diagnostics:[{source_path:'Settings.md',code:'existing_slug',message:'Existing article retained; select skip or explicit update before planning'}]},validation_issues:[{source_path:'Settings.md',code:'published_slug_reserved',message:'This slug belongs to another published revision; choose a different slug'}]};
const migrationOutcomes=['applied','skipped','failed','pending'].map(status=>({status,source_path:'Settings.md',post_id:'post-1',...(status==='failed'?{error:'Migration plan targets a different instance'}:{})}));
const views=[['proposal-diff',api.proposalReviewHTML(proposal,review)],['home',api.home()],['topics',api.topics()],['tag',api.tagPage('Drafts')],['about',api.about()],['login',api.login()],['editor',api.editorView()],['migration-plan',api.migrationPlanView(migrationReview)],['migration-complete',api.migrationReportView({complete:true,outcomes:migrationOutcomes})],['migration-partial',api.migrationReportView({complete:false,outcomes:migrationOutcomes})]];
for(const sample of ['Selected files: 3','Create 2 private drafts and replace 1 existing drafts.','Successful items are retained if a later item fails. Nothing is published. Retry this same frozen plan after any partial or unconfirmed result.','Keep reviewing','Ready to publish · Revision 3','/journal · 24 words · 2 min read','Currently live · R1','New version · R2','Publish revision 3','Changed: title, story content','Restore revision 2?','Revision 2 restored as a new draft.','This imports “Settings.json” into an empty FOLIO instance. The server verifies the checksum before importing. An instance with existing content cannot be restored over.'])assert.ok(i18n.resolve(sample),`dynamic dialog template: ${sample}`);
const allowed=/^(?:[0-9\s.,·/()+↗↑↓⌘✳-]*|Aa|B|I|H₂|<\/>|MARKDOWN|F \/ \d+|⌘K|Ctrl \/ ⌘ S|[0-9.]+ KB ·|v[0-9.]+|en|中文|EN)$/;
const missing=new Set();
function audit(name,html){const tree=parseHTML(html,document);for(const el of [tree,...tree.querySelectorAll('*')]){if(el.closest('[data-no-i18n],.prose,.code-sample,.tools-output,pre,code,script,style'))continue;if(!el.closest('textarea,time'))for(const node of el.childNodes){if(node.nodeType!==3)continue;const value=node.nodeValue.trim();if(value&&/[A-Za-z]/.test(value)&&!allowed.test(value)&&!i18n.resolve(value))missing.add(`${name}: ${value}`);}for(const attr of ['aria-label','title','placeholder']){const value=el.getAttribute(attr);if(value&&/[A-Za-z]/.test(value)&&!value.startsWith('/media/')&&!i18n.resolve(value,'attribute'))missing.add(`${name} [${attr}]: ${value}`);}}
 return tree;}
function assertEditorPlaceholders(tree,locale){for(const [id,key] of [['post-title','editor.title.placeholder'],['post-markdown','editor.body.placeholder'],['post-excerpt','editor.excerpt.placeholder']])assert.equal(tree.querySelector(`#${id}`).getAttribute('placeholder'),i18n.dictionaries[locale][key],`${id} placeholder is ${locale}`);}
for(const [name,html] of views){const tree=audit(name,html);i18n.setLocale('zh-CN');i18n.apply(tree);for(const node of tree.querySelectorAll('[data-no-i18n]'))assert.ok(!/设置|手记|暂时还没有活动记录/.test(node.textContent),'user text collision must not translate');if(name==='editor'){
 const fieldNodes=['post-title','post-markdown','post-excerpt'].map(id=>tree.querySelector(`#${id}`));const authoredText=fieldNodes.map(el=>el.textContent);
 for(const locale of ['zh-CN','en','zh-CN']){i18n.setLocale(locale);i18n.apply(tree);assertEditorPlaceholders(tree,locale);fieldNodes.forEach((el,index)=>{assert.equal(tree.querySelector(`#${el.getAttribute('id')}`),el);assert.equal(el.textContent,authoredText[index]);});}
}}

// Literal messages used by toast, validation, native confirms, and command data.
for(const match of source.matchAll(/'((?:[^'\\]|\\.)*)'/g)){const value=match[1];if(value.length>350||!/[A-Za-z]{2,} [A-Za-z]{2,}/.test(value)||/[<>\n{}]|var\(|\?\.|function|=>|document\.|^[#.]/.test(value)||value==='use strict')continue;if(!i18n.resolve(value.trim()))missing.add(`literal: ${value}`);}
(async()=>{
 context.fetch=async endpoint=>({ok:true,status:200,json:async()=>endpoint.includes('/api/public/posts/')?{post}:endpoint.includes('/api/public/search')?{posts:[post]}:{ok:true,data:endpoint.endsWith('proposals.list')?{proposals:[proposal]}:endpoint.endsWith('proposals.get')?{proposal,review}:endpoint.endsWith('posts.get')?{post}:endpoint.endsWith('schedules.list')?{schedules:[schedule]}:endpoint.endsWith('posts.list')?{posts:[post]}:endpoint.endsWith('settings.get')?{settings:api.state.site.settings,revision:1}:endpoint.endsWith('media.list')?{media:[{name:'Settings',url:'/media/pic.png',size:12000,created_at:post.created_at}]}:endpoint.endsWith('system.capabilities')?{operations}: {version:'0.1.0'}}});
 for(const [name,fn] of [['article',()=>api.article('journal')],['search',()=>api.searchPage('Settings')],['posts',()=>api.studioPosts()],['settings',()=>api.settingsPage()],['media',()=>api.mediaPage()],['tools',()=>api.toolsPage()],['proposals',()=>api.proposalsPage()],['proposal',()=>api.proposalsPage(proposal.id)],['schedules',()=>api.schedulesPage()],['migration-empty',()=>api.migrationPage()]])audit(name,await fn());
 api.state.migration={files:[{path:'Settings.md',content:'Save draft'}],conflict:'update',review:migrationReview,frozenPlanJSON:JSON.stringify(migrationReview.plan),report:{complete:false,outcomes:migrationOutcomes},locked:true,error:'The import result could not be confirmed. Preserve this frozen plan and retry it.'};
 const migrationTree=audit('migration-locked',await api.migrationPage()),migrationBefore=JSON.stringify(api.state.migration),protectedNodes=migrationTree.querySelectorAll('[data-no-i18n]'),protectedText=protectedNodes.map(node=>node.textContent);
 for(const locale of ['zh-CN','en','zh-CN']){i18n.setLocale(locale);i18n.apply(migrationTree);assert.ok(migrationTree.textContent.includes(i18n.dictionaries[locale]['migration.heading']));assert.ok(migrationTree.textContent.includes(i18n.dictionaries[locale]['migration.plan.retry']));assert.equal(JSON.stringify(api.state.migration),migrationBefore);protectedNodes.forEach((node,index)=>assert.equal(node.textContent,protectedText[index]));}
 assert.deepEqual([...missing],[],'hardcoded UI source audit');
 assert.equal(api.words('中文测试'),4);assert.equal(api.words('Hello 世界'),3);
 // Real saveDraft + locale engine, with an unresolved request and pending key.
 app.innerHTML=api.editorView();const fields=['post-title','post-slug','post-markdown','post-excerpt','post-tags','post-category','post-cover'];for(const id of fields){const field=document.getElementById(id);field.value=({ 'post-title':'Settings','post-slug':'journal','post-markdown':'Save draft','post-tags':'Drafts','post-category':'Journal'}[id]||'');}document.getElementById('post-featured').checked=false;
 const editorInput=document.getElementById('post-markdown');editorInput.focus();editorInput.selectionStart=2;editorInput.selectionEnd=5;editorInput.scrollTop=19;api.state.dirty=true;let resolveSave,request;
 context.fetch=async(endpoint,options)=>{request={endpoint,options};return await new Promise(resolve=>resolveSave=resolve);};
 i18n.setLocale('zh-CN');i18n.apply(app);assertEditorPlaceholders(app,'zh-CN');const editorSession=api.state.editor;const pendingSave=api.saveDraft(true);const pendingWrite=editorSession.pendingWrite;const key=pendingWrite.key;assert.equal(request.options.headers['Accept-Language'],'zh-CN');
 editorInput.value='Save draft\nNewer unsaved 内容';i18n.setLocale('en');assertEditorPlaceholders(app,'en');assert.equal(document.getElementById('post-markdown'),editorInput);assert.equal(api.state.editor,editorSession);assert.equal(editorSession.pendingWrite,pendingWrite);assert.equal(editorSession.pendingWrite.key,key);assert.equal(api.state.busy,true);assert.equal(document.activeElement,editorInput);assert.equal(editorInput.selectionStart,2);assert.equal(editorInput.selectionEnd,5);assert.equal(editorInput.scrollTop,19);assert.equal(editorInput.value,'Save draft\nNewer unsaved 内容');
 resolveSave({ok:true,status:200,json:async()=>({ok:true,data:{post:{...post,revision:2}}})});await pendingSave;i18n.apply();assert.equal(api.state.dirty,true);assert.equal(document.getElementById('save-state').textContent,'Unsaved changes');assert.equal(editorInput.value,'Save draft\nNewer unsaved 内容');i18n.setLocale('zh-CN');assertEditorPlaceholders(app,'zh-CN');assert.equal(document.getElementById('save-state').textContent,'有未保存的修改');assert.equal(document.activeElement,editorInput);
 console.log(`PASS: ${enKeys.length} bilingual keys/placeholder parity; default/storage/cookie/lang; live labels/ARIA/dates/counts/textarea placeholders; textarea content and explicit opt-outs preserved; content collisions; all-page and migration diagnostic source audit; CJK counts; dirty/in-flight state/caret/idempotency preserved; active Accept-Language`);
})().catch(err=>{console.error(err);process.exitCode=1;});
