// Source-level operation/DOM contract tests. Actual browser QA is separate.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {Element,parseHTML,createDocument}=require('./i18n-test-dom.cjs');
const root=path.join(__dirname,'..'),document=createDocument();
for(const id of ['app','modal-root','toast'])document.body.append(new Element('div',{id},document));
const location={origin:'http://localhost:8080',pathname:'/studio/proposals/p1',search:'',href:'http://localhost:8080/studio/proposals/p1'};
const context={console,Intl,Date,Map,Set,WeakMap,URL,URLSearchParams,JSON,Number,String,Array,Math,RegExp,Error,Promise,Blob,document,window:{addEventListener(){},scrollTo(){}},localStorage:{getItem:()=> 'en',setItem(){}},sessionStorage:{getItem:()=> 'test-token',setItem(){},removeItem(){}},location,history:{replaceState(){},pushState(_a,_b,url){const u=new URL(url,location.origin);location.pathname=u.pathname;location.search=u.search;}},navigator:{},crypto:{randomUUID:()=>Math.random().toString(16)},setTimeout:()=>1,clearTimeout(){},queueMicrotask:fn=>fn(),CustomEvent:class{constructor(type,{detail}){this.type=type;this.detail=detail;}}};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'i18n.js'),'utf8'),context);
const source=fs.readFileSync(path.join(root,'app.js'),'utf8').replace('  render();\n})();','  globalThis.test={state,can,proposalsPage,proposalReviewHTML,reviewProposalDecision,submitEditorProposal,schedulesPage,reviewSchedule,cancelSchedule,futureUTC,localDateInput,editorView};\n})();');vm.runInContext(source,context);const api=context.test;
const post={id:'post-1',title:'Settings',slug:'a-draft',excerpt:'No activity yet.',markdown:'Before\n<script>doNotRun()</script>',html:'<p>Before</p>',tags:['Drafts'],category:'Journal',revision:8,published_revision:3,created_at:'2026-10-03T12:00:00Z',updated_at:'2026-10-03T12:00:00Z'};
let proposal={id:'p1',post_id:post.id,base_revision:8,revision:1,status:'pending',created_by:'proposal',created_at:post.created_at,candidate:{...post,markdown:'After\n<img src=x onerror=doNotRun()>'},base:post};
const review={changed_fields:[{field:'markdown',before:post.markdown,after:proposal.candidate.markdown},{field:'title',before:'Journal',after:'Settings'}],markdown_diff:[{kind:'remove',text:post.markdown},{kind:'add',text:proposal.candidate.markdown}]};
let schedule={id:'s1',post_id:post.id,post_revision:3,snapshot:{...post,revision:3},revision:2,status:'pending',publish_at:'2030-01-01T12:00:00Z'};
const calls=[];let failApproval=false,loseSchedule=false;
const permissions=['posts.list','posts.get','posts.preview','posts.update','posts.publish','posts.restore','proposals.list','proposals.get','proposals.create','proposals.approve','proposals.reject','proposals.cancel','schedules.create','schedules.list','schedules.get','schedules.cancel','schedules.reschedule'];
api.state.info={actor:'admin',permissions,scheduler:{paused:true}};api.state.site={settings:{title:'FOLIO',author:'Writer',description:'Private content'},posts:[]};
context.fetch=async(endpoint,options={})=>{const name=endpoint.replace('/api/op/',''),body=JSON.parse(options.body||'{}');calls.push({name,body});let data={};if(name==='proposals.get')data={proposal,review};else if(name==='proposals.list')data={proposals:[proposal]};else if(name==='posts.get')data={post,revisions:[post]};else if(name==='posts.preview')data={post,html:post.html};else if(name==='schedules.get')data={schedule};else if(name==='schedules.list')data={schedules:[schedule]};else if(name==='proposals.approve'){if(failApproval)return {ok:false,status:409,json:async()=>({ok:false,error:{code:'conflict',message:'Revision conflict'}})};proposal={...proposal,status:'approved',revision:2,applied_post_id:post.id,applied_revision:9};data={proposal,post:{...post,revision:9}};}else if(name==='schedules.create'){if(loseSchedule){loseSchedule=false;throw new Error('Response lost');}schedule={...schedule,...body,revision:1,post_revision:body.expected_revision,snapshot:post};data={schedule};}else if(name==='schedules.reschedule'){schedule={...schedule,...body,revision:schedule.revision+1,post_revision:body.expected_post_revision,snapshot:post};data={schedule};}else if(name==='schedules.cancel'){schedule={...schedule,status:'cancelled',revision:3};data={schedule};}else if(name==='system.info')data=api.state.info;else if(name==='posts.list')data={posts:[post]};return {ok:true,status:200,json:async()=>({ok:true,data})};};
(async()=>{
 const diff=api.proposalReviewHTML(proposal,review);assert.ok(diff.includes('&lt;img'));assert.ok(diff.includes('&lt;script&gt;'));assert.equal(parseHTML(diff,document).querySelector('img'),null,'candidate text must never create executable image nodes');
 const detail=await api.proposalsPage('p1');assert.match(detail,/Approve to private draft/);assert.equal(api.state.proposalDetail.stale,false);const before=calls.length;api.reviewProposalDecision('approve');assert.equal(calls.length,before,'opening review must not mutate');failApproval=true;await document.querySelector('#workflow-confirm').onclick();assert.equal(calls.at(-1).name,'proposals.approve');assert.equal(calls.at(-1).body.expected_revision,1,'uses proposal revision, not draft revision');assert.equal(calls.at(-1).body.confirm,true);assert.match(document.querySelector('#workflow-error').textContent,/Nothing was overwritten/);assert.equal(calls.filter(c=>c.name==='posts.update'||c.name==='posts.publish').length,0);assert.equal(proposal.status,'pending');
 failApproval=false;await document.querySelector('#workflow-confirm').onclick();assert.equal(proposal.status,'approved');assert.equal(calls.filter(c=>c.name==='posts.publish').length,0,'approval never publishes');
 // Proactive stale baseline check disables approval even before the server guard.
 proposal={...proposal,status:'pending',revision:1,base_revision:7};const stale=await api.proposalsPage('p1');assert.equal(api.state.proposalDetail.stale,true);assert.match(stale,/data-proposal-decision="approve" disabled/);proposal={...proposal,base_revision:8};
 api.state.info={actor:'proposal',permissions:['posts.get','posts.preview','proposals.list','proposals.get','proposals.create','proposals.cancel']};assert.equal(api.can('proposals.approve'),false);assert.equal(api.can('schedules.create'),false);const scoped=await api.proposalsPage('p1');assert.ok(!scoped.includes('data-proposal-decision="approve"'));assert.match(await api.schedulesPage(),/Owner access is required/);
 api.state.info={actor:'admin',permissions,scheduler:{paused:true}};api.state.editor={post,revisions:[post]};api.state.dirty=false;location.pathname='/studio/posts/post-1';const scheduleView=await api.schedulesPage();assert.match(scheduleView,/Automatic publication is paused/);assert.match(scheduleView,/2030-01-01T12:00:00Z UTC/);assert.match(scheduleView,/Pinned revision 3/);
 const initial=calls.length;await api.reviewSchedule();assert.ok(calls.slice(initial).some(c=>c.name==='posts.preview'&&c.body.revision===8));assert.ok(!calls.slice(initial).some(c=>c.name==='schedules.create'));
 const field=document.querySelector('#schedule-at'),approved=document.querySelector('#schedule-approved');field.value=api.localDateInput(Date.now()+86400000);approved.checked=true;const expected=api.futureUTC(field.value);loseSchedule=true;await document.querySelector('#schedule-form').onsubmit({preventDefault(){},currentTarget:document.querySelector('#schedule-form')});const firstSchedule=calls.at(-1);assert.equal(firstSchedule.name,'schedules.create');assert.equal(firstSchedule.body.expected_revision,8);assert.equal(firstSchedule.body.publish_at,expected);assert.equal(firstSchedule.body.confirm,true);const pendingKey=firstSchedule.body.idempotency_key;context.window.FolioI18n.setLocale('zh-CN');assert.equal(field.value,api.localDateInput(new Date(expected)));await document.querySelector('#schedule-form').onsubmit({preventDefault(){},currentTarget:document.querySelector('#schedule-form')});const createCalls=calls.filter(c=>c.name==='schedules.create');assert.equal(createCalls.length,2);assert.equal(createCalls[1].body.idempotency_key,pendingKey,'lost response reuses schedule key');assert.deepEqual(createCalls[0].body,createCalls[1].body);assert.equal(schedule.post_revision,8);
 // A reschedule reviews current revision 8, rather than silently retaining 3.
 schedule={...schedule,post_revision:3,revision:4,status:'pending'};await api.reviewSchedule('s1');document.querySelector('#schedule-at').value=api.localDateInput(Date.now()+172800000);document.querySelector('#schedule-approved').checked=true;await document.querySelector('#schedule-form').onsubmit({preventDefault(){},currentTarget:document.querySelector('#schedule-form')});const reschedule=calls.findLast(c=>c.name==='schedules.reschedule');assert.equal(reschedule.body.expected_revision,4);assert.equal(reschedule.body.expected_post_revision,8);assert.equal(reschedule.body.confirm,true);
 await api.cancelSchedule('s1');await document.querySelector('#workflow-confirm').onclick();const cancel=calls.findLast(c=>c.name==='schedules.cancel');assert.equal(cancel.body.confirm,true);assert.ok(!('publish_at' in cancel.body));
 assert.throws(()=>api.futureUTC('2000-01-01T12:00'),/future/);assert.throws(()=>api.futureUTC('not-a-date'),/future/);assert.equal(calls.filter(c=>c.name==='posts.publish').length,0);
 console.log('PASS: escaped proposal diff; explicit private-draft approval; stale-base/role guards; paused warning; snapshot preview before schedule; local→UTC conversion; explicit revision/time confirmation; retry key; reschedule pins current draft; cancel never unpublishes');
})().catch(err=>{console.error(err);process.exitCode=1;});
